base_url = "https://waynee95.me"
title = "waynee95"
description = "my personal website"

[markdown]
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
smart_punctuation = true

[markdown.highlighting]
theme = "dracula"

[extra]
github_repo = "https://github.com/waynee95/waynee95.github.io"
math = true
