base_url = "https://waynee95.me"
title = "waynee95"
description = "my personal website"
generate_feed = true
sort_by = "date"

[markdown]
highlight_code = true
highlight_theme = "dracula"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
smart_punctuation = true

[extra]
github_repo = "https://github.com/waynee95/waynee95.github.io"
math = true
